---
- name: Add Discord repository key
  apt_key:
    url: https://dl.discordapp.net/apps/linux/keys.asc
    state: present
  become: true

- name: Add Discord repository
  apt_repository:
    repo: deb [arch=amd64] https://dl.discordapp.net/apps/linux/ {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Update apt package cache
  apt:
    update_cache: yes
  become: true

- name: Install Discord
  apt:
    name: discord
    state: present
  become: true
  # notify: Distrobox export app
