---
# https://www.omgubuntu.co.uk/install-discord-on-ubuntu-linux-mint

- name: Install Snapd
  ansible.builtin.apt:
    pkg:
    - snapd
  become: true

- name: Install Discord from Snap
  community.general.snap:
    name:
      - discord
  become: true
  # notify: Distrobox export app Snap